# Generated by Django 5.2.1 on 2025-05-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerifiedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="verified_videos/")),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("country", models.CharField(max_length=50)),
                ("has_snatching", models.BooleanField(default=False)),
            ],
        ),
    ]
