# Generated by Django 5.2.1 on 2025-05-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VerifiedVideo",
        ),
    ]
