# Generated by Django 5.2.1 on 2025-05-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employeereport_leaverequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="status",
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
