# Generated by Django 5.2.1 on 2025-05-27 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_remove_attendance_status_attendance_check_in_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaverequest",
            old_name="date",
            new_name="end_date",
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="admin_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="salary_deduction",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
