# Generated by Django 5.2.1 on 2025-05-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_rename_date_leaverequest_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
