# Generated by Django 5.2.1 on 2025-05-27 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_alter_leaverequest_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
